<?php


namespace Pixelant\Transliterator\DataHandling;


use Symfony\Component\String\Slugger\AsciiSlugger;
use TYPO3\CMS\Core\Site\Entity\Site;
use TYPO3\CMS\Core\Site\Entity\SiteLanguage;
use TYPO3\CMS\Core\Site\SiteFinder;
use TYPO3\CMS\Core\Utility\GeneralUtility;

class SlugHelper extends \TYPO3\CMS\Core\DataHandling\SlugHelper
{
    /**
     * @var SiteLanguage
     */
    protected $language = null;

    public function sanitize(string $slug): string
    {
        /** @var AsciiSlugger $slugger */
        $slugger = GeneralUtility::makeInstance(AsciiSlugger::class, $this->language->getLocale());

        return $slugger->slug($slug, ' ');
    }

    public function generate(array $recordData, int $pid): string
    {
        $languageFieldName = $GLOBALS['TCA'][$this->tableName]['ctrl']['languageField'] ?? null;
        $languageId = (int)($recordData[$languageFieldName] ?? 0);

        /** @var Site $site */
        $site = GeneralUtility::makeInstance(SiteFinder::class)->getSiteByPageId($pid);

        $this->language = $site->getLanguageById($languageId);

        return parent::generate($recordData, $pid); // TODO: Change the autogenerated stub
    }
}
